# Generated by Django 4.2.6 on 2024-06-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_alter_video_video_id'),
        ('playlists', '0003_playlist_videos_alter_playlist_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlist_item', to='videos.video'),
        ),
    ]
