# Generated by Django 4.2.6 on 2023-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_vidoe_id_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
