# Generated by Django 4.2.6 on 2023-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_delete_videoproxy_videoallproxy_videopublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Publish'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
    ]
